import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { SleepProfile as SleepProfileType } from "@/lib/profileGenerator";

interface SleepProfileProps {
  profile: SleepProfileType;
  onShare: () => void;
}

export const SleepProfile = ({ profile }: SleepProfileProps) => {
  return (
    <Card className="p-6 bg-gradient-to-br from-primary/5 via-purple-500/5 to-pink-500/5 border-primary/20">
      <div className="text-center space-y-4">
        <div className="text-6xl mb-2">{profile.profileIcon}</div>
        
        <h3 className="text-2xl font-bold">Your Sleep Profile</h3>
        
        <div className="grid grid-cols-2 gap-4 text-left">
          <div>
            <p className="text-sm text-muted-foreground">Sleep Position</p>
            <p className="font-semibold">{profile.sleepPosition}</p>
          </div>
          
          <div>
            <p className="text-sm text-muted-foreground">Firmness</p>
            <p className="font-semibold">{profile.firmness}</p>
          </div>
          
          <div>
            <p className="text-sm text-muted-foreground">Temperature</p>
            <p className="font-semibold">{profile.temperaturePreference}</p>
          </div>
          
          <div>
            <p className="text-sm text-muted-foreground">Support Needs</p>
            <div className="flex flex-wrap gap-1 mt-1">
              {profile.supportNeeds.slice(0, 2).map((need, i) => (
                <Badge key={i} variant="secondary" className="text-xs">
                  {need}
                </Badge>
              ))}
            </div>
          </div>
        </div>
        
        <div className="pt-4 border-t">
          <p className="text-xs text-muted-foreground">
            Generated by Mattress Wizard AI 🛏️
          </p>
        </div>
      </div>
    </Card>
  );
};
